%% Rewritten Prolog - Mathematical Induction Form
%% Generated by mi.pl

%% Derived Closed-Form Formulas
%% Closed-form for sum_integers/2:
%%   Coefficients: [0.0,0.5,0.5,0.0]
%%   Formula: 0.0 + 0.5*n + 0.5*n^2 + 0.0*n^3



%% Generated Test Cases
:- begin_tests(mi_generated).

test(derived_sum_integers/2) :- true. % TODO: Add validation tests
test(no_patterns) :- true.
:- end_tests(mi_generated).
